### ISSUE TITLE
Tracking fails with add new particles selected

### ISSUE THREAD

**Issue by lengelen** [lengelen/pyptv#5]
Dear developers/users,

I tested the latest pyptv using images of three cameras.
Running sequence without display works perfect, and when i clock detected particles the software shows the position of the particles in green. Herewith, the rt_is files are created as supposed to.
Running track without display with 'add new particles' in Tracking parameters performs well, and I get reasonably good trajectories. However, when I enable this flag, the software adds new lines to the rt_is files with the last -1 (corresponding to the fourth camera) to 0 for some of the found particles.

Since the particles are then listed twice in the rt_is file, the found trajectories stop very quickly.
I added 3 consecutive rt_is files, with and without the 'add new particles' flag to clarify my issue.

Any ideas on this matter?

[rt_is_withflag.zip](https://github.com/lengelen/pyptv/files/2612356/rt_is_withflag.zip)
[rt_is_withoutflag.zip](https://github.com/lengelen/pyptv/files/2612357/rt_is_withoutflag.zip)

**Comment by lengelen** [comment]
@alexlib any ideas?

**Comment by alexlib** [comment]
will take a look. 

please explain which branch do you use and which test case

**Comment by lengelen** [comment]
Dear Alex,

I use the latest branch Update/clean-up. Any test case will do. 
I checked with e.g. test_cavity and there the problem also occurs.

**Comment by alexlib** [comment]
i cannot reproduce the error. please repeat again, precisely the steps that create the problem.

**Comment by lengelen** [comment]
Dear Alex,

The problem apparently only arises when 3 cameras are used.
As an example, I added a test folder of a recent experiment: [folder](https://github.com/lengelen/pyptv/tree/Update/clean-up/tests/test_0911-alex).
You will see that the rt_is files contain duplicates of the same particles which results in problems with tracking.

**Comment by alexlib** [comment]
@lengelen I tried it with test_3cam but it didn't do what you got. So I suspect one of the following:
a) you have a different liboptv branch
b) the order of operations is important. 

let's see how do we make it so I can reproduce it - otherwise I cannot debug it: 
1. in the terminal go to liboptv folder and try `git status`, let's be both on `origin/master` where `origin` is the github.com/openptv/openptv.git
2. the same we need for the `pyptv`, just to be sure we're on the same page
3. start with a clean folder (no results) and write down the order of operations. 

thanks

**Comment by alexlib** [comment]
I see it now @lengelen - when I run Sequence I get correct rt_is. files and when afterwards I run tracking, the rt_is files are changed with the additional zeros at the end. However, I do not understand the problem as the tracking works fine for me. Does it fail for you? What do you try to do with the rt_is files besides using them again in tracking?

**Comment by lengelen** [comment]
@alexlib, Have you tried the test case that I uploaded in the Update/clean-up branch under tests?
If you run it there, you will see that I get less-optimal trajectories, in which a single trajectory is split up in several parts. I added a screenshot of the ptv_is.1000088 of this test case as an example. As you can see, the particle with location (117.920;-45.246;0.559) is detected twice in the rt_is files and not properly linked.
![splitupparticles](https://user-images.githubusercontent.com/22395487/49209619-4234f180-f3bb-11e8-882e-4ccbe556eb2b.png)

**Comment by alexlib** [comment]
I see now. Thanks for pointing it out. Could you please check if PBI does it as well? It'll help me to think of a problem

**Comment by alexlib** [comment]
@lengelen please - check if PBI has the same problem. I start digging into this and it's rather deep. `pyptv` does not write targets as far as I understand during tracking procedure, but it does it in `sequence`. on one hand apparently it writes the right list, but probably something is not compatible with the following tracking and the option to add particles. I do not know where to look first.

**Comment by lengelen** [comment]
@alexlib , I am afraid I never got PBI working with three cameras. When I run PBI, it gives me 0 correspondences for the test case of @yosefm with three of the four cameras in the config file.

I would like to help to solve the problem, but have no idea where to look??

**Comment by yosefm** [comment]
liboptv does write targets and particles during tracking. The way it works is that there is a frame buffer holding 4 frames at a time. Each time a frame finishes processing, the exiting frame is written back, the buffer is rotated, and the entering frame is loaded to the front of the buffer.

I would look in trackcorr_c_loop to see how a new particle place is decided. This particle is then added to the frame by calling `add_particle()` in track.c, and then written back out.

I'm sorry that I don't have time this weekend for an in-depth debug session, but if you don't make progress by next weekend, I'll make my best effort to dedicate time.

**Comment by alexlib** [comment]
@yosefm @lengelen this is definitely a bug. for an easier tracking I suggest to work with the [test_2cam](https://github.com/alexlib/test_2cam) - it adds 1 and 2 particles to the `rt_is.10003` and `rt_is.10004` frame, respectively. If you look at the particle id - it shows clearly that it's a double particle - same IDs appear above in the same file 

https://github.com/alexlib/test_2cam/commit/7320244802a5d07d71d5b492eb266267fab33752

**Comment by lengelen** [comment]
I have tried to look for the problem, but could not find a solution so far...
I checked and it appears that the particles that are duplicated correspond to larger particle accelerations:
when I reduce the ` dacc ` in the tracking parameters, I obviously find less links but only links that do not have the problem remain (e.g. in the  test_2cam to `dacc=0.2`)

Therefore, I assume that the problem has something to do with too many candidates in `trackcorr_c_loop`. I know I didn't find much, but it's something ...

Any ideas @alexlib @yosefm ?

**Comment by alexlib** [comment]
I'm circling around the question of how do we choose the possible candidates to be added and why there's a difference for the less than 4 cameras cases. So far I have a problem to understand @yosefm why in the old code we had different `candsearch_in_pix` that was used for all candidates 

https://github.com/OpenPTV/openptv-python/blob/535c94676ab173b680b2b0f95a5bd9a44ae06fe7/src_c/ttools.c#L62
but `candsearch_in_pixrest` for the added particles

https://github.com/OpenPTV/openptv-python/blob/535c94676ab173b680b2b0f95a5bd9a44ae06fe7/src_c/ttools.c#L143

maybe the different search mechanism was some way to prevent choosing the already marked particles? or maybe we have some broken link that when particles are selected they are not marked properly.

**Comment by alexlib** [comment]
@yosefm I think I'm right about the bug place - we have to use a different  `candsearch_in_pix` because when we look for all the candidates, we do the search for neighbours  

https://github.com/OpenPTV/openptv-python/blob/535c94676ab173b680b2b0f95a5bd9a44ae06fe7/src_c/ttools.c#L62
but `candsearch_in_pixrest` for the added particles

which are not `-1`, i.e. identified already. 

https://github.com/OpenPTV/openptv-python/blob/535c94676ab173b680b2b0f95a5bd9a44ae06fe7/src_c/ttools.c#L101


https://github.com/OpenPTV/openptv-python/blob/535c94676ab173b680b2b0f95a5bd9a44ae06fe7/src_c/ttools.c#L178

    `  if (next[j].tnr == -1 ) {`

it's a different logic - use only those which are `-1`, i.e. not used
